### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by Duck1en** [Duck1en/groupie-tracker-app#4]
make this responsive
![image](https://user-images.githubusercontent.com/60964945/174632841-87efb3bc-813a-4085-b35e-29df00eb1326.png)

**Comment by Rshezarr** [comment]
Responsive issue is fixed
![Screenshot from 2022-06-21 18-34-15](https://user-images.githubusercontent.com/66269334/174804948-26fabcf0-47df-45f1-8319-1e2a486867df.png)
